### ISSUE TITLE
Broken TLS support on SDK Version 16

### ISSUE THREAD

**Issue by tjg1** [tjg1/nori#103]
Tests are failing on older versions of Android, due to outdated TLS support.

If this only affects unit tests, we could switch to using http for affected test cases.

## Travis Log

```
Starting 79 tests on test(AVD) - 4.1.2

io.github.tjg1.library.norilib.test.DanbooruLegacyTest > testSearchAsync[test(AVD) - 4.1.2] FAILED 

	java.io.IOException: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.

	at io.github.tjg1.library.norilib.clients.DanbooruLegacy$1.onCompleted(DanbooruLegacy.java:184)

io.github.tjg1.library.norilib.test.DanbooruLegacyTest > testSearchUsingTags[test(AVD) - 4.1.2] FAILED 

	java.io.IOException: java.util.concurrent.ExecutionException: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.

	at io.github.tjg1.library.norilib.clients.DanbooruLegacy.search(DanbooruLegacy.java:166)

io.github.tjg1.library.norilib.test.DanbooruLegacyTest > testSearchUsingTagsAndOffset[test(AVD) - 4.1.2] FAILED 

	java.io.IOException: java.util.concurrent.ExecutionException: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.

	at io.github.tjg1.library.norilib.clients.DanbooruLegacy.search(DanbooruLegacy.java:166)

io.github.tjg1.library.norilib.test.DanbooruTests > testSearchAsync[test(AVD) - 4.1.2] FAILED 

	java.io.IOException: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.

	at io.github.tjg1.library.norilib.clients.Danbooru$1.onCompleted(Danbooru.java:184)

io.github.tjg1.library.norilib.test.DanbooruTests > testSearchUsingTags[test(AVD) - 4.1.2] FAILED 

	java.io.IOException: java.util.concurrent.ExecutionException: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.

	at io.github.tjg1.library.norilib.clients.Danbooru.search(Danbooru.java:164)

io.github.tjg1.library.norilib.test.DanbooruTests > testSearchUsingTagsAndOffset[test(AVD) - 4.1.2] FAILED 

	java.io.IOException: java.util.concurrent.ExecutionException: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.

	at io.github.tjg1.library.norilib.clients.Danbooru.search(Danbooru.java:164)

io.github.tjg1.library.norilib.test.ServiceTypeDetectionServiceTest > testDanbooruDetection[test(AVD) - 4.1.2] FAILED 

	java.lang.AssertionError: expecting actual not to be null

	at io.github.tjg1.library.norilib.test.ServiceTypeDetectionServiceTest.testDanbooruDetection(ServiceTypeDetectionServiceTest.java:42)

io.github.tjg1.library.norilib.test.ServiceTypeDetectionServiceTest > testDanbooruLegacyDetection[test(AVD) - 4.1.2] FAILED 

	java.lang.AssertionError: expecting actual not to be null

	at io.github.tjg1.library.norilib.test.ServiceTypeDetectionServiceTest.testDanbooruLegacyDetection(ServiceTypeDetectionServiceTest.java:51)

io.github.tjg1.library.norilib.test.ServiceTypeDetectionServiceTest > testShimmieDetection[test(AVD) - 4.1.2] FAILED 

	java.lang.AssertionError: expecting actual not to be null

	at io.github.tjg1.library.norilib.test.ServiceTypeDetectionServiceTest.testShimmieDetection(ServiceTypeDetectionServiceTest.java:69)

:norilib:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':norilib:connectedDebugAndroidTest'.

> There were failing tests. See the report at: file:///home/travis/build/tjg1/nori/norilib/build/reports/androidTests/connected/index.html

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 53.44 secs

The command "./gradlew :norilib:connectedAndroidTest" exited with 1.
```

**Comment by tjg1** [comment]
Turns out that it's a bug in AndroidAsync (Ion's dependency). 

Temporarily downgrading ion to 2.1.7 seems to fix the issue.

See: https://github.com/koush/AndroidAsync/issues/512
