### ISSUE TITLE
Crash when restoring state of suspended activities

### ISSUE THREAD

**Issue by tjg1** [tjg1/nori#28]
Steps to reproduce: Reopen Nori after it's been suspended by the OS and the Activity state has to be restored at launch.

### logcat

```
07-24 00:16:56.185 32461 32461 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cuddlesoft.nori/com.cuddlesoft.nori.ImageViewerActivity}: android.util.AndroidRunti
meException: Window feature must be requested before adding content
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-24 00:16:56.185 32461 32461 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: Window feature must be requested before adding content
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7.throwFeatureRequestIfSubDecorInstalled(AppCompatDelegateImplV7.java:1711)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7.requestWindowFeature(AppCompatDelegateImplV7.java:585)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.support.v7.app.AppCompatActivity.supportRequestWindowFeature(AppCompatActivity.java:227)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at com.cuddlesoft.nori.ImageViewerActivity.onCreate(ImageViewerActivity.java:99)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6251)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
07-24 00:16:56.185 32461 32461 E AndroidRuntime:        ... 9 more
```

**Comment by tjg1** [comment]
Fixed in 8c1ba1.
